#!/bin/bash

# Descripción:	Script que recibe parametro un fichero de texto y lee todas sus líneas,
#		mostrando la longitud de cada línea y al final cuantas lineas
#		tiene el fichero

if [ $# -ne 1 ]; then
	echo "Error de sintaxis. SE espera solo un parámetro"
	echo "Sintaxis: $0 <archivo de texto>"
	exit 1
fi

if [ ! -f $1 ]; then
	echo "Archivo no válido, tiene que ser un archivo regular"
	exit
fi



#comprobar que sea un archivo de texto

TIPOARCHIVO=`file --mime-type -b $1 | cut -f1 -d/`
echo "el tipo de archivo es $TIPOARCHIVO"
if [ "$TIPOARCHIVO"  != "text" ]; then 
	echo "el tipo de archivo no es compatible"
	exit 3
fi


#leemos el fichero



while read LINEA  ;do

let ++NUM_LINEA
echo "Nº de línea: $NUM_LINEA"
echo "linea: $LINEA"
echo "La liena tiene ${#LINEA} caracteres"

done < $1
echo "Fin de recorrido del fichero $1"
echo "El archivo $1 tiene ${NUM_LINEA} lineas"


